export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_COMPLETED = 'AUTH_LOGIN_COMPLETED'
export const AUTH_FALTURE = 'AUTH_FALTURE'
export const REGISTER_COMPLETED= 'REGISTER_COMPLETED'